# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19gBOimVSRoGtGEoHvCZKT38wCUFss1dc

LISTA EM PYTHON
"""





'''lista_media = []
lista_notas = [[10,9,8],[7,8,5],[4,9,8],[10,8,10],[10,4,5],[10,10,10]]
nome = input('qual seu nome ? ')
nota = sum(lista_notas[0])
media = nota / len(lista_notas[0])
print('olá',nome,'sua nota é',media)
lista_media.append(media)

nome1 = input('qual seu nome ? ')
nota1 = sum(lista_notas[1])
media1 = nota1 / len(lista_notas[1])
print ('olá',nome1,'sua nota é',media1)
lista_media.append(media1)


nome2 = input('qual seu nome ? ')
nota2 = sum(lista_notas[2])
media2 = nota2 / len(lista_notas[2])
print ('olá',nome2,'sua nota é',media2)
lista_media.append(media2)


nome3 = input('qual seu nome ? ')
nota3 = sum(lista_notas[3])
media3 = nota3 / len(lista_notas[3])
print ('olá',nome3,'sua nota é',media3)
lista_media.append(media3)


nome4 = input('qual seu nome ? ')
nota4 = sum(lista_notas[4])
media4 = nota4 / len(lista_notas[4])
print ('olá',nome4,'sua nota é',media4)
lista_media.append(media4)


nome5 = input('qual seu nome ? ')
nota5 = sum(lista_notas[5])
media5 = nota5 / len(lista_notas[5])
print('olá',nome5,'sua nota é',media5)
lista_media.append(media5)

lista_de_media = []
lista_de_media +=(media,media1, media2,media3,media4,media5)
maior =  max(lista_de_media)
print(f'Maior média, {maior:.2f}')
media_geral_classe = sum(lista_de_media)/len(lista_de_media)
print(f'Média geral, {media_geral_classe:.2f}')'''



VENDAS = {
'SETOR1':{
'MÊS 1':[150,200,300]},
'SETOR2':{
'MÊS 2':[300,250,300]},
'SETOR3':{
'MÊS 3':[15,20,300]},
'SETOR4':{
'MÊS 4':[150,2000,300000],
}
}
lista_media = []
print(VENDAS.items())
media = sum(VENDAS['SETOR1']['MÊS 1'])/len(VENDAS['SETOR1']['MÊS 1'])
print(media)
lista_media.append(media)

media = sum(VENDAS['SETOR2']['MÊS 2'])/len(VENDAS['SETOR2']['MÊS 2'])
print(media)
lista_media.append(media)

media = sum(VENDAS['SETOR3']['MÊS 3'])/len(VENDAS['SETOR3']['MÊS 3'])
print(media)
lista_media.append(media)

media = sum(VENDAS['SETOR4']['MÊS 4'])/len(VENDAS['SETOR4']['MÊS 4'])
print(media)
lista_media.append(media)

maior =  max(lista_media)
print(f'Maior venda, {maior:.2f}')
menor = min(lista_media)
print(f'Menor venda, {menor:.2f}')